### ISSUE TITLE
Cron Jobs - Last number is missing in the date/time selectors

### ISSUE THREAD

**Issue by Sopor** [virtualmin/authentic-theme#1542]
What has happening with the cron jobs? As you can see here the minutes, hours, days etc need to be scrolled to see all the numbers. I'm pretty sure it wasn't like this before:

![image](https://user-images.githubusercontent.com/5789283/119401867-66e45880-bcdc-11eb-9048-b3152137e820.png)

It is quite annoying to move every scrollbar to see if one of them are selected or not :(

**Comment by Sopor** [comment]
I manage to find an old picture and as you can see here i'm not forced to scroll everyone of them:

![image](https://user-images.githubusercontent.com/5789283/119402762-af504600-bcdd-11eb-8727-9bc4d702dcd0.png)

**Comment by iliarostovtsev** [comment]
Hi, Sopor.

Could you please install the latest dev version of the theme and see if this is still an issue?

**Comment by Sopor** [comment]
19.76-beta4-2 and yes, it is the same :(

**Comment by iliarostovtsev** [comment]
What browser and OS is that?

After installing latest _19.76-beta4-2_ were the clone and delete buttons displayed again as expected?

**Comment by iliarostovtsev** [comment]
Of course it's Firefox "feature". It just adds `2px` top and bottom padding around option in selects.

**&nbsp;&nbsp;&nbsp;Chrome&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Firefox**
![image](https://user-images.githubusercontent.com/4426533/119465843-bb272100-bd4c-11eb-93e3-db230ce25ac0.png) ![image](https://user-images.githubusercontent.com/4426533/119465712-97fc7180-bd4c-11eb-8ddb-d946a4c90d92.png) 

Fixed.


Thanks a lot for reporting!

**Comment by Sopor** [comment]
Yes, i'm running Firefox and now it is fixed :)
