### ISSUE TITLE
Custom commands page has very odd look and feel. Please look at CSS

### ISSUE THREAD

**Issue by swilson563** [virtualmin/authentic-theme#1544]
Hello, since upgrading the Custom Commands page has a very odd look at feel.

The layout is not as smooth as past releases.

It appears to be css related.

**Comment by iliarostovtsev** [comment]
Hi,

Could you please provide a screenshot and share in private message `/etc/webmin/custom` directory so I could see what is wrong exactly?

**Comment by swilson563** [comment]
![webmin -authentic](https://user-images.githubusercontent.com/52164766/119988798-1a26a900-bf8c-11eb-8caf-15611f141e40.png)
![webmin - bootstrap](https://user-images.githubusercontent.com/52164766/119988811-1c890300-bf8c-11eb-9365-fdcaebe3e7ec.png)


Here are two comparisons.  The authentic theme has very little spacing between commands.  The text box is near zero in size and by the title looks odd without being in a DIV block.  The other is the bootstrap theme which has some spacing and ordering of parameters.

**Comment by swilson563** [comment]
Ok, It looked very nice on version 1.7.X
We upgraded to the latest and my users complained that it looked odd.

Thanks
Scott

**Comment by iliarostovtsev** [comment]
>  It looked very nice on version 1.7.X

Again, can you please be exact about on which version it looked nice? What is 1.7.x? We don't have such versioning. Could you share more on how it looked before and how it looks now and the content of `/etc/webmin/custom` directory? You can use my personal website to send me download link(s) privately.

**Comment by swilson563** [comment]
This is webmin version 1.881
Theme version Authentic Theme <https://github.com/qooob/authentic-theme>
 19.09.2

[image: image.png]


Attached are the files you requested.  I had to add a "_" for gmail to
accept.

Thanks
Scott

**Comment by iliarostovtsev** [comment]
I received and replied to your email. Please attach **`/etc/webmin/custom`**, and I'll review it on how it looks to understand if there is anything wrong.

**Comment by swilson563** [comment]
It was the zip file in my last email

Scott

**Comment by iliarostovtsev** [comment]
> It was the zip file in my last email

I am sorry, Scott, never received it. Could you please send it over again?

**Comment by iliarostovtsev** [comment]
I got it now. Alright, I don't think I like current output that much but the way it was before is even worse in my opinion. 

>  Since upgrading the Custom Commands page has a very odd look at feel.

What is it in current layout/output that makes it feel bad for you? Current layout is made to fit as much as possible in a single line, with adjustable input box.

FYI, you could use **Custom Commands ⇾ Configuration: Configurable options** to switch to **Links to commands** table like output. Also you could keep the current output but display it in one column instead of two as set right now by default.

**Comment by swilson563** [comment]
The team that uses this page think things are too close together so they
get confused on which input fields belong with which buttons

Also, the small text field causes them to not enter data cause they think
it is limited in size.

They like inputs being vertical so they know to set each value

Thanks
Scott

**Comment by swilson563** [comment]
Some custom command that we build are 4 or 5 inputs and trying to fit
horizontally with labels make it hard to input

We have about 20 commands on the page. I could go to one page to listing if
you don’t want to change. Team might go for that layout

Scott

**Comment by iliarostovtsev** [comment]
> We have about 20 commands on the page. I could go to one page to listing if you don’t want to change.

I would like to improve it, I think!

Can you just send me the list of real life custom commands that you use, so I could prevision on what your team expects? I'll keep them safe, no worries here.

**Comment by iliarostovtsev** [comment]
Now, I understand what you meant by saying "it has very odd look and feel". Infact, with more advanced application it had a ridiculous layout -- it was barely usable! I have never used it that way. Sorry.

I've spent considerable amount of time today to have it fix but I also left the old mode working for more simple commands:


![image](https://user-images.githubusercontent.com/4426533/140620424-95f3cdd8-cc4e-45a0-a19d-50449e54bdf5.png)

Next theme release will have it fixed. Sorry for taking so long. I didn't realise there was such a serious oversight!

**Comment by iliarostovtsev** [comment]
Fix responsiveness for Custom Commands module and few other minor bugs.

Uploaded [examples of custom commands](https://github.com/virtualmin/authentic-theme/files/7492161/webmin-custom-commands-example.zip) for the future reference.

**Status:** Fully accomplished.
