### ISSUE TITLE
Title bar will not change version but dashboard will

### ISSUE THREAD

**Issue by Sopor** [virtualmin/authentic-theme#1546]
I got this message after updating my RPi:
`Warning - Your system is actually running Raspbian Linux version 10.`
and that is correct and after i pressed the button it will update the version on the dashboard but it will not update the title bar as you can see here:

![image](https://user-images.githubusercontent.com/5789283/120938015-0c51f000-c711-11eb-8967-3426f545cf19.png)

Maybe you could force an update of the page so the title bar also will change version when i press that button?

**Comment by iliarostovtsev** [comment]
Hi, Sopor!

Thanks for the heads up. Fixed.
