### ISSUE TITLE
Authentic-theme issues

### ISSUE THREAD

**Issue by aunbrandtfreidank** [virtualmin/authentic-theme#1547]
Installed latest version of Webmin version 1.974-1
Navigated to https://fqdn:10000 and https://ip:100000 page takes a long time to load and receive a login prompt with no formatting. Reviewing developer tools console in Google Chrome version 91.0.4472.77 displays the following:

net::ERR_EMPTY_RESPONSE https://<server_ip>:10000/unauthenticated/css/bundle.min.css?19729999999999900
net::ERR_EMPTY_RESPONSE https://<server_ip>:10000/unauthenticated/css/fonts-roboto.min.css?19729999999999900
net::ERR_EMPTY_RESPONSE https://<server_ip>:10000/images/favicons/webmin/favicon-32x32.png
net::ERR_EMPTY_RESPONSE https://<server_ip>:10000/images/favicons/webmin/favicon-16x16.png
net::ERR_EMPTY_RESPONSE https://<server_ip>:10000/images/favicons/webmin/android-chrome-192x192.png

If you try to login it fails with the following in the developer tools console:
crbug/1173575, non-JS module files deprecated.

Rolled back theme using:  ./theme-update.sh -release:19.72 and restarted webmin, cleared browser cash and reloaded the page however the issue persists.

NOTE: Setting ssl=0 in /etc/webmin/miniserv.conf and restarting webmin resolves this but is a less than ideal workaround.

**Comment by iliarostovtsev** [comment]
Hello,

This is certainly not the theme issue nor the issue directly related to Webmin.

However, here are the few things you could try. 

First of all, try turning off all browser's plugins or trying incognito tab first (where all plugins must be disabled by default) and/or try different browser.

If that wouldn't work, try restarting Webmin with **`systemctl restart webmin`** command. If restarting Webmin changes nothing, and Webmin restarts without any issue, you can manually edit **`/etc/webmin/miniserv.conf`** and temporarily set **`ssl=0`** (disable SSL) and restart Webmin. This will help you to login using _**http://**_ and figure out later what is going wrong with SSL.
