### ISSUE TITLE
Update 19.75 to 19.80

### ISSUE THREAD

**Issue by rolandheymanns** [virtualmin/authentic-theme#1548]
Hi Ilia,
updating from 19.75 to 19.80 ends up back in 19.75
Cheers
Roland

**Comment by iliarostovtsev** [comment]
Hi, Roland.

You are right, I updated the script to let it work correctly when the theme repo is moved to a new organization.

**Comment by iliarostovtsev** [comment]
By the way, if you need to upgrade the theme right now, simply choose to _install latest devel version_ from the dropdown.

**Comment by XhmikosR** [comment]
@iliarostovtsev have you thought about cutting a new stable with the fix?

**Comment by iliarostovtsev** [comment]
> have you thought about cutting a new stable with the fix?

Yes, I will look into making 19.80 or 19.80.1 tomorrow.

**Comment by iliarostovtsev** [comment]
19.81 was tagged.

**Comment by XhmikosR** [comment]
@iliarostovtsev thanks! But I'm still getting in the update loop :/ I'm using 19.75 and Webmin 1.974.

I tried force install stable, same thing.

**Comment by FBachofner** [comment]
@XhmikosR -- can confirm, still have an update loop as well.  On Ubuntu Server 20.04.2 / Webmin 1.974

Force-install _beta_ works . . .

**Comment by iliarostovtsev** [comment]
There will be an update loop unless you update the **`theme-update.sh`** script with the latest version manually.
