### ISSUE TITLE
Dashboard question

### ISSUE THREAD

**Issue by MorningSleeper** [virtualmin/authentic-theme#1553]
Hi, don't know if this is part of Authentic Theme or not but if so what is the distinction between the red and blue lines in the Disk I/O and Network I/O graphs on the dashboard?

![image](https://user-images.githubusercontent.com/8920632/123457382-b8605b80-d598-11eb-9d47-6ced3a98aa5c.png)

**Comment by iliarostovtsev** [comment]
Hello,

Those are I/O (input/output) for network and disk data.

Try uploading something to your server in the background, while staying on the Dashboard to see what happens.
