### ISSUE TITLE
Document title format is <Module — >regardless the configuration setting

### ISSUE THREAD

**Issue by pacquo** [virtualmin/authentic-theme#1554]
(Webmin 1.979 with Authentic Theme 19.82, installed on Ubuntu 20.04.2)
The page title is always in the form `module_name em_dash`, like _Theme Configuration —_, _Dashboard —_ and so on, and no longer respect the scheme selected in Theme Configuration / Document title format.

**Comment by iliarostovtsev** [comment]
Hello,

That is odd. If you go to Theme Configuration, change the document title format, save the changes and try opening some other module page, does it work?

It works for me, as I just tried it.

**Comment by pacquo** [comment]
Hello Ilia,
I've tried that, but it doesn't work. Normally I use the default (Module - Webmin version (OS type), but even selecting some other option, the result does not change. 
(Note: Webmin has been installed from the _minimal_ version).

**Comment by pacquo** [comment]
Solved. I verified a backup of a previous installation of Webmin (1.973) and I noticed that in the `config` file under `etc/webmin` the parameter `nohostname` was set to "0", while in the current version was set to "1". Changing the value of `nohostname`  to 0 solved the issue.

**Comment by iliarostovtsev** [comment]
This is wrong, I will fix that.

**Comment by iliarostovtsev** [comment]
It will be fixed in upcoming 19.83 release.

Thanks for reporting.
