### ISSUE TITLE
ConfigServer Security & Firewall 14.10

### ISSUE THREAD

**Issue by palaboy** [virtualmin/authentic-theme#1555]
ConfigServer Security & Firewall 14.10 page is blank, cannot access.

**Comment by iliarostovtsev** [comment]
Hi,

It works for me. Have you tried hard-reloading the page (clearing all the cache).

Do you have any error messages on the browser's console?

What Webmin and Authentic Theme version do you have instaled?

**Comment by palaboy** [comment]
Clearing cookies and site data not working on firefox v90.0.2, i try other browser ms edge but it works.
Webmin v1.979 - Authentic Theme v19.81

**Comment by iliarostovtsev** [comment]
I think I know what the issue is, and I'm starting to remember fixing it few weeks ago.

Please use Theme Configuration page to install latest development version of the theme. It'll work.

**Comment by palaboy** [comment]
Yes thanks it works problem solved, i just updated to latest version 19.82
