### ISSUE TITLE
stats history not updating

### ISSUE THREAD

**Issue by Glujaz** [virtualmin/authentic-theme#1556]
Hello there,

I'm coming to you because of a stats history not working when I'm offline from webmin. I'm not using the admin user but a secondary user who has admin rights, is it because of that ? 
I couldn't find anything explaining why it's not working.

My system : core2duo with 4GB of ram running on Debian 10. All up to date.

Thanks in advance for your reply,

**Comment by iliarostovtsev** [comment]
Hello,

> I'm coming to you because of a stats history not working when I'm offline from webmin.

This is designed. The browser's window must be open to collect history. Moreover the browser's window is expected to be focused unless _Enable real-time monitoring_ set to _Yes, force_ on **Theme Configuration: Dashboard and real-time monitoring** page.
