### ISSUE TITLE
cronjob - can't move the cursor all the way to the right

### ISSUE THREAD

**Issue by Sopor** [virtualmin/authentic-theme#1557]
If i add (maybe there is no reason to do as i do, but it shouldn't behave like it do)
```
sopor              /usr/local/bin/script-renew-sopor.sh /var/log/script-renew/sopor
```
to a cronjob as a command i can't scroll to the right.

In the picture below you can see the text is cut off to the right and i can't use my mouse, my arrow keys or the end key to go any further to the right and show all the chars.

![image](https://user-images.githubusercontent.com/5789283/128273751-8ee108b0-e4b8-48f2-90d6-af581933e113.png)

But if i add (or remove) a couple of spaces like this
```
sopor                  /usr/local/bin/script-renew-sopor.sh /var/log/script-renew/sopor
```
i can move the cursor all the way to the right.

Windows 10 x64 1909
Firefox 90.0.2
Webmin 1.979
Authentic theme 19.83-RC4-3

**Comment by iliarostovtsev** [comment]
Hi, Sopor.

You are right, as I can also see this happening in my Firefox 90.0.2 on Linux. However, this is purely Firefox bug.

If you wish, you could add the following to the theme extensions (CSS) to work-around the problem.

```CSS
#content input.form-control.ui_textbox[type="text"] {
  padding-right: 0
}
```
