### ISSUE TITLE
Why "Hide Table Icons" options has been removed from 19.82?

### ISSUE THREAD

**Issue by cpuga** [virtualmin/authentic-theme#1559]
I haven't found any comments on issues or changelogs about this change. 
I'll have to keep 19.81 until this options returns. :(

**Comment by iliarostovtsev** [comment]
Hi,

I just decided to remove it in the process of making UI look simpler. I thought it is not used anymore by anyone.

Sorry.

Perhaps, using small icons would help?

You can enable small icons by running in the browser's console:

```JavaScript
settings_right_small_table_icons = true;
theme.config.save();
```

**Comment by cpuga** [comment]
Hi, thanks for the quick reply.

I agree to look for a cleaner UI,  that's why I always use webmin without the table icons... :)

- They  make more difficult to find a section link. The links table layout is more readable, has no titles on 1,2 or 3 lines which makes them misaligned and is much more compact and clean
- They make the page slower (several additional requests for gifs because they aren't a icon font like fontawesome)
- Talking about fontawesome, they don't match the style of the fontawesome icons you're using in buttons, tabs,... Actually the Nuvola icon set used (from 2004) seems outdated in comparison

I hope that you will reconsider this design decision. 
Thank you for your great work in any case.

Just 2 screenshots to prove my points:

![Captura de pantalla 2021-09-13 a las 17 57 09](https://user-images.githubusercontent.com/775810/133119573-1f944758-dd77-4d61-9e2b-5f55bceb1c5f.png)
![Captura de pantalla 2021-09-13 a las 17 57 25](https://user-images.githubusercontent.com/775810/133119613-4045f14c-b28b-4151-af18-31c0567fd742.png)

**Comment by iliarostovtsev** [comment]
Considering that you're asking for it and being reasonable and also I know how bad it may feel for devs just to remove features that were there, I will re-add it for 19.84 release.

I will update this ticket when it happens.

And the icon theme should be refreshed. It's also on my list of to-dos.

**Comment by cpuga** [comment]
Great! I'll be looking forward to see this release.
Thanks.

**Comment by iliarostovtsev** [comment]
This has be re-implemented anew, with better responsiveness and better table options.

**Examples:**

![image](https://user-images.githubusercontent.com/4426533/135770886-2fe9a9ce-5318-4800-85a4-b9854b09631f.png)


![image](https://user-images.githubusercontent.com/4426533/135770902-ab1ee410-efe4-4795-8d35-82b7e0e0f616.png)
![image](https://user-images.githubusercontent.com/4426533/135770916-e910e65c-fe2e-46bc-b83c-d7cff476a8df.png)
![image](https://user-images.githubusercontent.com/4426533/135770921-41d727c6-d9c2-41c4-9ad7-92cabed9c310.png)
![image](https://user-images.githubusercontent.com/4426533/135770955-acb5bd68-fdf7-4f7d-80fa-d1c97576399f.png)

**Comment by cpuga** [comment]
Thanks! :)
