### ISSUE TITLE
Files not saving in File Manager after Webmin update

### ISSUE THREAD

**Issue by MatthewHolmes** [virtualmin/authentic-theme#1560]
We've just updated to Webmin 1.981, Virtualmin 6.16, Authentic theme version 19.83-2. We're running Ubuntu Linux version 18.04.5.  
The File Manager has stopped saving files. We're getting this error in the DevTools console:

`bundle.min.js?19839999999999902:458 Uncaught TypeError: e.replaceAll is not a function
    at bundle.min.js?19839999999999902:458
    at Array.forEach (<anonymous>)
    at Object.htmlUnEscapeSafe (bundle.min.js?19839999999999902:458)
    at __footer_message (bundle.min.js?19839999999999902:461)
    at HTMLFormElement.<anonymous> (bundle.min.js?19839999999999902:461)
    at HTMLFormElement.dispatch (bundle.min.js?19839999999999902:2)
    at HTMLFormElement.v.handle (bundle.min.js?19839999999999902:2)
    at Object.trigger (bundle.min.js?19839999999999902:2)
    at HTMLFormElement.<anonymous> (bundle.min.js?19839999999999902:2)
    at Function.each (bundle.min.js?19839999999999902:2)` 

Clearing cache and restarting Webmin hasn't helped.

**Comment by iliarostovtsev** [comment]
Hi, Matthew.

If you install very latest 19.84-beta1 from theme configuration page, does it change anything for you? I fixed few small bugs just recently, perhaps it would affect your case.

However, it works for me with clean Webmin 1.981 install on all systems I tried, i.e. I can save the file.

**Comment by MatthewHolmes** [comment]
Hi Ilia,

Thanks for getting back to me and for checking. Looks like it's an issue in Chrome, probably on my system. It's working in Safari.

**Comment by iliarostovtsev** [comment]
Thanks for the feedback. I'll test it on my Mac tomorrow.

What if you use incognito tab in Chrome, does it help?

What exact Chrome version do you use?

**Comment by MatthewHolmes** [comment]
Incognito didn't make any difference interestingly.  It's Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by iliarostovtsev** [comment]
Chrome 84 is over 1 year old. Current Chrome version is 93. Can you consider upgrading and trying again?

**Comment by MatthewHolmes** [comment]
Wow! Autoupdate's clearly not working!  I'll give it a go when I can and let you know.
