### ISSUE TITLE
Webmin: Tools: [System and Server Status]: [Scheduled Monitoring] is Broken

### ISSUE THREAD

**Issue by Shanto** [virtualmin/authentic-theme#1561]
When using Authentic Theme, navigating to this page results in a half done (broken) page:

Path UI Path: System & Server Status: Scheduled Monitoring (edit_sched.cgi)
Full URL of right-side iframe: /status/edit_sched.cgi?xnavigation=1

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/821784/137993944-b3f801b7-80c4-440d-bc33-c0dd744ee02a.png">

**Comment by iliarostovtsev** [comment]
Yes, all displayed correctly as expected.

If you temporarily clear the module config, and refresh the page, does it fix it?

**Comment by Shanto** [comment]
Hi @iliarostovtsev, I tried–

1. Temporarily zeroing the config file. Didn't help.
2. Temporarily removing all monitored services (empty ./services dir). Didn't help.
3. Triggered a new config creation by hitting Save from one of the legacy framed Themes. Didn't help either.

I tried to debug browser-server communication to troubleshoot this problem. I find that only when using Authentic theme, the output of edit_sched.cgi from server ends prematurely right after outputting this particular table row:

```                                            <tr>
                                                <td class='col_label'>
                                                    <b>From: address for email</b>
                                                </td>
                                                <td colspan="3" class="col_value">
                                                    <span class="awradio awobject">
                                                        <input class="iawobject" type="radio" name="from_def" value="1" checked id="from_def_1_721" onClick='e = form.elements["from"]; e.disabled = true; for(i=0; i<e.length; i++) { e[i].disabled = true; } '>
                                                        <label class="lawobject" for="from_def_1_721">Default (webmin)</label>
                                                    </span>
                                                    <span class="awradio awobject">
                                                        <input class="iawobject" type="radio" name="from_def" value="0" id="from_def_0_721" onClick='e = form.elements["from"]; e.disabled = false; for(i=0; i<e.length; i++) { e[i].disabled = false; } '>
                                                        <label class="lawobject" for="from_def_0_721">&nbsp;</label>
                                                    </span>

                                                    <span>
                                                        <input class='ui_opt_textbox form-control' style='display: inline; width: auto; height: 28px; padding-top: 0; padding-bottom: 2px;' type='text' name="from" size=30 value="">
                                                    </span>
                                                </td>
                                            </tr>
```

This doesn't happen with framed themes. Any advice?

**Comment by iliarostovtsev** [comment]
If you try browser's incognito mode does it help? If you try other browser without extensions installed, does it change anything?

If non of this works, can I please login and have a look?

**Comment by iliarostovtsev** [comment]
Any update on this?

**Comment by Shanto** [comment]
Hi @iliarostovtsev it seems that one of my content blockers was breaking this. I am extremely sorry for wasting your time on this. I should have checked this first before filing a bug report.

**Comment by iliarostovtsev** [comment]
Do you know which content blocker was it exactly?
