### ISSUE TITLE
Error - Perl execution failed Undefined subroutine &main::authentic called at /usr/libexec/webmin/authentic-theme/index.cgi line 12.

### ISSUE THREAD

**Issue by NAHIDKHKAN** [virtualmin/authentic-theme#1563]
How can i fixed??

**Comment by NAHIDKHKAN** [comment]
after update this webmin verson then occured error
Error - Perl execution failed
Undefined subroutine &main::authentic called at /usr/libexec/webmin/authentic-theme/index.cgi line 12.

**Comment by iliarostovtsev** [comment]
Hi,

You shouldn't install it solely without Webmin update. There is a dependency.

It is better to downgrade the theme to the previous version or just use a package manager to reinstall whole Webmin package.

What distro and version this is? What Webmin version do you have installed? Does restarting Webmin helps?

**Comment by jcameron** [comment]
@iliarostovtsev can we add some kind of version dependency check in the theme to prevent this?

**Comment by jcameron** [comment]
So we block the upgrade entirely if webmin isn't compatible?

**Comment by iliarostovtsev** [comment]
> So we block the upgrade entirely if webmin isn't compatible?

With 19.84.1 release, it won't be possible to update the theme easily using UI in case of incompatibilities.
