### ISSUE TITLE
Why will CSF show update on the dashboard but not on the second computer?

### ISSUE THREAD

**Issue by Sopor** [virtualmin/authentic-theme#1564]
I have several Webmin running and two of them are running CSF.

On computer one the dashboard will show when an update is available:
**Dashboard**
![image](https://user-images.githubusercontent.com/5789283/142253687-ffa31b00-ba82-47fe-8e4d-6f0e388e734f.png)

But on computer two i need to open CSF to see if there is a new update:
**Dashboard**
![image](https://user-images.githubusercontent.com/5789283/142254045-3c3a696a-71c2-4b99-941c-d1eb43b0a044.png)

**CSF**
![image](https://user-images.githubusercontent.com/5789283/142254076-5ed43676-bc1a-41b6-a5a3-41de133cd19f.png)

I'm running the exact same Webmin/Authentic theme and CSF on both computers.

The only thing that is different is the OS. Computer one is running `Raspbian Linux 10` and computer two is running `Ubuntu Linux 18.04.6`

I can't find any options either to change it. Why will it look so different?

**Comment by iliarostovtsev** [comment]
Hi, Sopor.

> On computer one the dashboard will show when an update is available:

This is because it was disabled, I presume by setting **`settings_sysinfo_csf_updates`** to **`false`** manually.

You can open browsers console on computer two, copy/paste **`settings_sysinfo_csf_updates`** and hit enter to see its value.

If value is **`false`**, then you should set it to default **`true`** permanently by saving configuration afterwards:

```
settings_sysinfo_csf_updates = true;
theme.config.save();
```

**Comment by Sopor** [comment]
How long will this changes be saved?

When i search for `settings_sysinfo_csf_updates` it will select over 3800 chars :(

I can't remember that i have disabled it. In that case it must have been you that helped me :)

**Comment by iliarostovtsev** [comment]
Click **`F12`** to open browser console and then paste **`settings_sysinfo_csf_updates`** and hit enter.

**Comment by Sopor** [comment]
I have done that and it will select hundreds of `settings_`

**Comment by iliarostovtsev** [comment]
Don't type. Just paste **`settings_sysinfo_csf_updates`**

**Comment by Sopor** [comment]
I paste it on the line `Search HTML` and press enter.

**Comment by iliarostovtsev** [comment]
No, no.. paste to the browsers console tab:

![image](https://user-images.githubusercontent.com/4426533/142273132-beaea2e8-0591-4556-b0b9-306257f6e7fc.png)

**Comment by Sopor** [comment]
I manage to do as you explained to me, but now there is no update button on the CSF page as my computer two has.

There must be something else that makes these have different looks.

**Comment by Sopor** [comment]
**Computer two on the CSF page:**
![image](https://user-images.githubusercontent.com/5789283/142278401-bc7fb15b-d79a-4dc7-a145-ac279d289d36.png)

**Computer one on the CSF page:**
![image](https://user-images.githubusercontent.com/5789283/142278475-46bec782-0142-4afa-aee7-e40024479f68.png)

**Comment by iliarostovtsev** [comment]
Look, i don't remember exactly what could cause it but you can check this option in CSF module config:

![image](https://user-images.githubusercontent.com/4426533/142279304-50a7dedd-2883-49da-8485-1891101f0a21.png)


.. also you can using command line to upgrade CSF, like:

Check:
```
csf -u
```

or 

Force upgrade:

```
csf -uf
```

**Comment by Sopor** [comment]
If  you don't know why it is like this, it must be something CSF have changed and the only difference between these two computers are the OS. I haven't changed any settings either.

**Comment by iliarostovtsev** [comment]
On which OS it doesn't work?

**Comment by Sopor** [comment]
I don't know if something is broken or not. I only see that they are different.
Computer one that is running:
```
Linux 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - Ubuntu Linux 18.04.6
```
will **not** show any updates, changelog or download buttons on the dashboard. All these buttons are only visible on the CSF page.

Computer two that is running:
```
Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux - Raspbian Linux 10
```
will show updates, changelog or download buttons on the dashboard and have no buttons for it.

It is strange that CSF has moved the buttons without your knowledge or is it possible to do that if you do modules for Webmin like CSF do?

**Comment by Sopor** [comment]
You haven't figured out yet, why they look different?

**Comment by iliarostovtsev** [comment]
I wasn't able to reproduce it. I could login and figure out pretty easily.

**Comment by iliarostovtsev** [comment]
Sopor, start from checking if your server can connect at all to _CSF_ update server, try running on the console:

```
host download.configserver.com      # in my case 94.130.90.175
host configserver.com.              # in my case 66.165.246.164
ping download.configserver.com
ping configserver.com
```

.. and check the output.

When using console, can you download the file, on that non-working server, by running:

```
wget https://download.configserver.com/csf.tgz
```

**Comment by Sopor** [comment]
I don't have a non-working server. I only have different ways that CSF shows the updates.

**Comment by iliarostovtsev** [comment]
That's what I meant. Theme doesn't control how updates are shown on CSF module itself. So try my suggestions and report back.

**Comment by Sopor** [comment]
Yes, i have tried it and it is the same.

When i have updated both CSF everything looks the same. It is only when there is a new update there will be differences in how i update them.

```
$ wget https://download.configserver.com/csf.tgz
--2021-12-11 18:47:10--  https://download.configserver.com/csf.tgz
Resolving download.configserver.com (download.configserver.com)... 94.130.90.175
Connecting to download.configserver.com (download.configserver.com)|94.130.90.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2282408 (2.2M) [application/x-gzip]
Saving to: ‘csf.tgz’

csf.tgz                               100%[=======================================================================>]   2.18M  2.22MB/s    in 1.0s

2021-12-11 18:47:11 (2.22 MB/s) - ‘csf.tgz’ saved [2282408/2282408]
```

```
~$ wget https://download.configserver.com/csf.tgz
--2021-12-11 18:47:15--  https://download.configserver.com/csf.tgz
Resolving download.configserver.com (download.configserver.com)... 94.130.90.175
Connecting to download.configserver.com (download.configserver.com)|94.130.90.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2282408 (2.2M) [application/x-gzip]
Saving to: ‘csf.tgz’

csf.tgz                               100%[=======================================================================>]   2.18M  5.23MB/s    in 0.4s

2021-12-11 18:47:16 (5.23 MB/s) - ‘csf.tgz’ saved [2282408/2282408]
```

**Comment by iliarostovtsev** [comment]
> When i have updated both CSF everything looks the same. It is only when there is a new update there will be differences in how i update them.

Does the update button show on both servers if you go to the module?

Does the update prompt show equally on the dashboard on both servers?

> When i search for settings_sysinfo_csf_updates it will select/find over 3800 chars :( I can't remember that i have disabled it. In that case it must have been you that helped me :)

If you open browser's console, paste and run (hit enter), what output do you get on server one and on server two:

```JS 
if (1===1) {console.log(settings_sysinfo_csf_updates)};
```

**Comment by Sopor** [comment]
> Does the update button show on both servers if you go to the module?

No.

> Does the update prompt show equally on the dashboard on both servers?

No.

> If you open browser's console, paste and run (hit enter), what output do you get on server one and on server two:

It will show this on both computers:
![image](https://user-images.githubusercontent.com/5789283/145687145-d26533bd-8454-4dea-b3d3-809911cc31fe.png)

There are not any updates right now. I have updated them both to 14.15.

**Comment by iliarostovtsev** [comment]
> There are not any updates right now. I have updated them both to 14.15.

You can edit **`/etc/csf/version.txt`** file manually for testing purposes.

> It will show this on both computers

This output looks wrong to me.

What Webmin and theme version do you have intalled?

Either way, try the following:

   1. Run the following on the browser console:
   ```
   settings_sysinfo_csf_updates = true;
   theme.config.save();
   ```
   2. Change _CSF_ version on the mentioned file above
   3. _Clear Cache_ by using theme config page or using right side slider (dropdown from cog icon) or holding _all modifier_ keys together and hitting _R_

> You haven't figured out yet, why they look different?

I hope you don't mean why there is 14.11 and 14.15 don't match??

**Comment by Sopor** [comment]
> I hope you don't mean why there is 14.11 and 14.15 don't match??

Both computers was running 14.11 before i updated them.

> What Webmin and theme version do you have installed?

Both are running: `Webmin version 1.983 | Authentic theme version 19.84.6`

> You can edit **`/etc/csf/version.txt`** file manually for testing purposes.

I edit the file version.txt and changed it from 14.15 to 14.11.
I then did clear cache in the Webmin dashboard.
Now CSF is announcing that there is a new version to install, 14.15 and now it looks different.

Computer one will show on the dashboard that there is an update for CSF as you can see here:
![image](https://user-images.githubusercontent.com/5789283/145694547-38332d4a-6b59-46b3-9a62-91d5ba1c1445.png)

Computer two will not show it on the dashboard as you can see here:
![image](https://user-images.githubusercontent.com/5789283/145694572-6ac9437a-43eb-4779-bbfe-0f6d461265c3.png)

If i want to see CSF updates on computer two i have to click on `ConfigServer Security & Firewall` to open CSF's page:
![image](https://user-images.githubusercontent.com/5789283/145694651-8da8839c-a405-4ed8-b9c4-d870cb743fe5.png)

I want to have it like computer two on both computers (it has been like computer two the past two three years, but suddenly has computer one moved the update and changelog buttons to the dashboard). I don't want to see the updates on the dashboard. I want to have it like it was before, i have to open the CSF page to see if there is an update.

If i do as you suggested in the beginning `settings_sysinfo_csf_updates = false` it will turn off the update completely and that is not what i want. Both have `settings_sysinfo_csf_updates` set to `true` now as they have been all the time.

So, why do one of the computers show an Update, Changelog and a Download button on the dashboard, but not the other one?

**Comment by iliarostovtsev** [comment]
I have read your last comment on the email, but I am not sure why you have deleted it here.

You mentioned that "I don't want to see the updates on the dashboard." -- well, no problem, even though it's not clear to me why you wouldn't want to see updates on the Dashboard, it's easily doable by opening browser's console and running:

```
settings_sysinfo_csf_updates = false;
theme.config.save();
```

You also mentioned "If i do as you suggested in the beginning `settings_sysinfo_csf_updates = false` it will turn off the update completely and that is not what i want." -- this _must_ not be the case, this option only controls what theme does and has no influence on the module itself, as you will see that update button on the module disregard of that option.

Either way, I don't recommend disabling showing updates on the Dashboard as it doesn't add up any value but disabling it, using suggested above way, won't hide showing updates on CSF module page.

**Comment by Sopor** [comment]
I have no idea what is going on, but i manage to get the buttons for updating CSF to go away from the dashboard by entering
```
settings_sysinfo_csf_updates = false;
theme.config.save();
```
When i did that before there wasn't any update button on the CSF page as the other computer. I still wanted to update CSF, so your suggestion wasn't working, but now it worked.

Maybe it has been a bug and CSF has made some changes how it will show? I'm totally confused ...

**Comment by Sopor** [comment]
I deleted it because it is working now.

I don't want the dashboard clean and not full of other stuff. I want to see the same buttons on the dashboard. If all programs should show buttons when there are new messages or new updates it should be a mess.

**Comment by iliarostovtsev** [comment]
I am glad it is fixed for you.

**Comment by Sopor** [comment]
Sorry, but after changing `settings_sysinfo_csf_updates` to false it will not show any updates at all on either the dashboard or on the CSF page.

The other computer will show the update on the CSF page `/csf/index.cgi?xnavigation=1` and my goal was not to disable showing updates. I wanted it to show up on the CSF page on both computers.

So, here is still something that make this happen that none of us understand why this is happening.

Maybe the CSF team knows?

**Comment by iliarostovtsev** [comment]
Hi, Sopor!

This subroutine is responsible for remote version check on ConfigServer
Security FIrewall side:

sub manualversion {
    my $current = shift;
    my $upgrade = 0;
    my $url = "https://$config{DOWNLOADSERVER}/csf/version.txt";
    if ($config{URLGET} == 1) {$url = "http://
$config{DOWNLOADSERVER}/csf/version.txt";}
    my ($status, $newversion) = $urlget->urlget($url);
    if (!$status and $newversion ne "" and $newversion =~ /^[\d\.]*$/ and
$newversion > $current) {$upgrade = 1} else {$newversion = ""}
    return ($upgrade, $newversion);
}

I don't know *exactly *what the issue is on your side but it must be very
easy to figure out.

  1. Check that you can connect/download from your server
*download2.configserver.com/csf/version.txt
<http://download2.configserver.com/csf/version.txt>* and
*download2.configserver.com/csf/version.txt
<http://download2.configserver.com/csf/version.txt>* files both using *http*
and *https *protocols
  2. Check the content of */etc/csf/downloadservers* file which should
contain domains mentioned above
  3. Alternatively, try installing *libwww-perl* module (apt-get install
libwww-perl)
  4. Also, go to ConfigServer Security FIrewall *configuration page* and
search for *URLGET* option, and take a guess which should/could be used (by
the way, which one is set right now?)
  5. Eventually, check for csf -c command output

Anyway, this is *not the theme issue*, as if you change the theme to the
Gray Framed theme you will face the same issue (where you cannot see
upgrade prompt on CSF main page)

Kind regards,
Ilia

**Comment by iliarostovtsev** [comment]
Hi, Sopor!

This subroutine is responsible for remote version check on ConfigServer
Security FIrewall side:

~~~
sub manualversion {
    my $current = shift;
    my $upgrade = 0;
    my $url = "https://$config{DOWNLOADSERVER}/csf/version.txt";
    if ($config{URLGET} == 1) {$url = "http://
$config{DOWNLOADSERVER}/csf/version.txt";}
    my ($status, $newversion) = $urlget->urlget($url);
    if (!$status and $newversion ne "" and $newversion =~ /^[\d\.]*$/ and
$newversion > $current) {$upgrade = 1} else {$newversion = ""}
    return ($upgrade, $newversion);
}
~~~

I don't know *exactly *what the issue is on your side but it must be very
easy to figure out.

  1. Check that you can connect/download from your server *download2.configserver.com/csf/version.txt* and *download2.configserver.com/csf/version.txt* files both using *http* and *https* protocols

  2. Check the content of */etc/csf/downloadservers* file which should
contain domains mentioned above

  3. Alternatively, try installing *libwww-perl* module (apt-get install
libwww-perl)

  4. Also, go to ConfigServer Security FIrewall *configuration page* and
search for *URLGET* option, and take a guess which should/could be used (by
the way, which one is set right now?)

  5. Eventually, check for `csf -c` command output

Anyway, this is *not the theme issue*, as if you change the theme to the
Gray Framed theme you will face the same issue (where you cannot see
upgrade prompt on CSF main page)

Kind regards,
Ilia

**Comment by iliarostovtsev** [comment]
Sopor, any update on this issue?

**Comment by Sopor** [comment]
I have checked all the above suggestions and both have the exact same settings, versions and installations.

The only thing that is different, is the OS as i already have mentioned.

**Comment by Sopor** [comment]
I created a new topic on the CSF forum 03/22, but it seems that they don't want other users to help me because the moderators haven't even publish my post: 🙁
```
This post is not visible to other users until it has been approved by a moderator.
```

**Comment by iliajie** [comment]
Please send me the link.

**Comment by Sopor** [comment]
@iliajie `https://forum.configserver.com/viewtopic.php?t=12445`

**Comment by iliajie** [comment]
I have emailed you details in private.
