### ISSUE TITLE
File manager: Upload to current directory popup not working in 18.84.4

### ISSUE THREAD

**Issue by sintos** [virtualmin/authentic-theme#1565]
After upgrading from 18.83 to 18.44.4 the popup window that should appear when selecting "Upload to current directory" in File Manager, is gone.
It is not displaying at all.
After downgrading to 18.83 everything returns to normal.

**Comment by iliarostovtsev** [comment]
Hi, 

It needs upgraded File Manager module (`filemin` from Webmin repo), which hasn't been released yet.
