### ISSUE TITLE
mysql password widget disapeared

### ISSUE THREAD

**Issue by aqueos** [virtualmin/authentic-theme#1568]
hi there,

I noticed  since the latest webmin upgrade 1.982 and authentic theme 19.84.5

Version Webmin | 1.982 | 
Version Usermin | 1.823
Version Virtualmin | 6.17-3 | 
Version de thème authentique | 19.84.5

that the password for mysql can be changed but the 2 icons for seeing the password and for generating a new password have both disapeared from the form.

![Screenshot from 2021-11-30 11-02-43](https://user-images.githubusercontent.com/7724531/144026600-bc030cd1-fc57-48d5-b449-801e02237bae.png)
.

Is that normal ?

best regards,
Ghislain.

**Comment by iliarostovtsev** [comment]
Hi, Ghislain.

No, looks like a regression.

**Comment by iliarostovtsev** [comment]
Fixed. Give it a try by upgrading using **Theme Configuration: Theme updates** page.
