### ISSUE TITLE
Button text cannot be seen. Perl 500 errors. Dashboard theme text is white box.

### ISSUE THREAD

**Issue by forlotto** [virtualmin/authentic-theme#1571]
Some things I noticed after update.
-Perl 500 errors everywhere.
-Button text is as white as the buttons cant read it on select buttons.
-Dashboard theme text displays at white box.

Dunno what happened after last update but holy moly wish I wouldn't have updated to a large degree I cannot even try to install Bacula without one perl error after another. 

It seems to work very well otherwise but it renders the UI/UX useless in many aspects with all of the errors don't know what has changed really or how to downgrade need to keep website up and running this is important will have to do bare metal backup and have a server shutdown for a day. 
![Button Text Example Previous Next missing text](https://user-images.githubusercontent.com/29682719/146654640-93fa1e69-4824-4705-9221-25be108e57df.png)
![Perl 500 errors showing up](https://user-images.githubusercontent.com/29682719/146654649-62c6c56e-a623-4b34-be86-6209e14e3132.png)
![Theme text buttons white boxes](https://user-images.githubusercontent.com/29682719/146654653-ad1a8064-a47c-4609-9843-dd182aa6349a.png)

**Comment by iliarostovtsev** [comment]
Hi,

You need to update Usermin to the latest version to be able to use Authentic Theme 19.84.

**Comment by forlotto** [comment]
odd it is not coming up on the repo's as upgradable maybe its a deb buster thing? Would be nice to be able to see if anyone else is having the issue. I will attempt to find and update after I do a backup don't want to cause other potential issues I am using virtualmin. Which has webmin, usermin, and virtualmin kinda allpacked together. So potentially there is no release cause they are adding other patches for log4j or I may be on stable release channel for all I know errr been a while since I configured will have to look into it further thank you for the quick response.

**Comment by iliarostovtsev** [comment]
The version of Usermin in Virtualmin repos is behind those could be found and installed from official Webmin site.

We are not affected _log4j_ bug.

**Comment by forlotto** [comment]
updated my comment holy moly what a quick rx.

**Comment by iliarostovtsev** [comment]
It means you manually updated the theme ignoring the warning message. This shouldn't be done.

Try reinstalling Usermin (to get supported theme version back) or installing latest Usermin version from Webmin site manually.

**Comment by forlotto** [comment]
Out of curious nature why isn't the latest package on the repo? Is there other bugs that it potentially causes? I guess I am unsure I may just have to enable night mode and deal with it and hope for the later version to be released on the repo. I'd rather not screw things up at current don't have the time for bare metal backup or revamping the entire server at the moment too much going on. Took quite some time to get it setup how I wanted it kinda don't want to lose that progress I have one backup with a lot of stuff missing. Thank you for your time.

**Comment by forlotto** [comment]
Performed the latest update to usermin however the same problem still exists it is possible webmin will need updating too I am unsure of what the warning message said could you share it with me?

**Comment by iliarostovtsev** [comment]
No, you just need to restart Usermin that's all.

**Comment by forlotto** [comment]
Did not work still getting perl errors as well maybe I shall restart the entire server with a power down and clear cache for themes.

**Comment by forlotto** [comment]
Reboot of server did not help either.

**Comment by iliarostovtsev** [comment]
If you stop Webmin, restart Usermin and then try, what result do you get?

**Comment by forlotto** [comment]
Same thing even if switching between grey framed theme and back to authentic theme.

**Comment by forlotto** [comment]
Also how do we donate to help keep this project alive is there a crypto currency I can purchase or paypal donation button etc....

**Comment by iliarostovtsev** [comment]
Look, it seems that Usermin upgrade went wrong.

Try upgrading/reinstalling it over again. And please double check that _pids_ actually change when you restarting it.

Also, I assume you have one Usermin instance installed and running? 🙂

This error shouldn't happen as this new sub supposed to be found in some of the files in Usermin installation directory. Try searching through the files' contents to see if it's there, like `grep -Ril path/to/usermin/dir foreign_func_exists`.

I will double check this on my side tomorrow, but I'm pretty sure I haven't seen this error before when was running tests.

Thank you for your desire to contribute! The best way to contribute on the regular basis is to buy Virtualmin Pro license. It is also possible to contribute one time using one of the methods found on the main page of Authentic Theme repo.

**Comment by forlotto** [comment]
I want to support GPL development I guess this is important to me pro versions I get it they are needed for large business and really you shouldn't have to have both if large business was just honest and contributed the proper amount to development why would you need 10 different methods of buying virtualmin or cloudmin etc... It don't entirely make sense to me as to why people don't support things and properly fund them without being forced to but I also understand this is the case. So where I can donate to that I will donate to that. 

Back to the issue at hand I did attempt to reinstall usermin and it doesn't appear that it helps as for errors the direction things are being pointed it seems as if webmin requires the update if I had to guess however I am not sure as you would be the wiser on this subject.  My webmin version is 1.981 if this helps.

**Comment by iliarostovtsev** [comment]
> It don't entirely make sense to me as to why people don't support things and properly fund them without being forced to but I also understand this is the case.

I think in most cases people tend to think that they won't make any difference by their small commitments.

> Back to the issue at hand I did attempt to reinstall usermin and it doesn't appear that it helps as for errors the direction things are being pointed it seems as if webmin requires the update if I had to guess however I am not sure as you would be the wiser on this subject. 

Webmin and Usermin are stand-alone apps and supposed to work without any interaction. I checked it on my side and it seems to work as expected.

**Summary** - For **Authentic Theme 19.84** to work you need at least **Webmin 1.982** and/or **Usermin 1.832**. You could install those from [here](https://download.webmin.com/devel/deb/). Give it a try and tell me if there is still an issue for you.

**Comment by forlotto** [comment]
Perl errors gone buttons came back as 4 colored buttons then I refreshed the page and can't see the button text again I dunno this is goofy I wish there was not theme update that wasn't supposed to be installed to be honest if it wouldn't have came up I would've never upgraded but hey one step closer. Yes I tried the usual reinstalling and switching back and forth between themes clearing cache and restarting the server. Maybe Virtualmin needs an update as well for all I know I can't call it personally. 

But these dang buttons suck man not being able to read half the buttons but at least I can reconfigure Bacula that's a plus.

Yeah errr what is your paypal you know you are the one helping me out there I'd much rather just donate directly to you at this point as I see you all over the place helping with this project! If you could share that information somehow I'd be glad to donate.

**Comment by forlotto** [comment]
Look above restart webmin button there are buttons like this all over but thank god the hideous white background is now grey and the PERL errors are gone it seems thus far.

![look above restart webmin button](https://user-images.githubusercontent.com/29682719/147036407-23d972c8-ddfe-4927-a06f-4cd534b599cc.png)

I am curious I do want to donate where can I find the button as well having trouble locating the donation address.
