### ISSUE TITLE
Username Generator

### ISSUE THREAD

**Issue by tpnsolutions** [virtualmin/authentic-theme#1572]
Hey, I think it'd be cool if either in the theme or Virtualmin there could be a "username" generator. Similar to how there's a setting in Virtualmin Configuration, it would be neat if this feature allowed you to define a "pattern", then generated a random username based on this.

I commonly use usernames like "u1234" where each username starts with "u" and ends with a 4-digit number. I've considered making this a bit better by introducing having a username start with a letter from "a-z" and ending in a 4-digit number...

Right now I have a shell script which I use to interact with the API whereby I generate a random password, and random username which is passed to the API to generate Virtual Servers.

Having the ability to randomly generate a password based on pattern would making doing this in the UI a possibility without having to generate the username somewhere else first.

Thanks for the consideration!

**Comment by jcameron** [comment]
Sure, we could do this.

Alternately, what if the username was generated from the new user's real name?

**Comment by tpnsolutions** [comment]
Well I think that could be an option but I'm a fan of short usernames that can are supported natively by multiple services with truncating for instance.

I believe if there were a "pattern" the generator was based on it'd be more flexible.

**Comment by jcameron** [comment]
Ok .. the tricky part would be defining a format for the admin to enter the username pattern. Maybe something like `%1s%4d` for your one-letter four-numbers style?

**Comment by tpnsolutions** [comment]
How about a "regex" expression like:

[a-z]{1}[0-9]{4}

This would generate something like:

a1234
b2345
etc...

In my current situation, I'd have written the expression like:

u[0-9]{4}

Which would then generate something like:

u1234
u2345
etc...

**Comment by iliarostovtsev** [comment]
Good idea. I could add this.

**Comment by tpnsolutions** [comment]
Kew :-)

**Comment by jcameron** [comment]
@iliarostovtsev send me the pull request if you go ahead with implementing this..

**Comment by iliarostovtsev** [comment]
@jcameron Sure, Jamie! 🙂 Will do! 🎄

**Comment by iliarostovtsev** [comment]
I have just added a [new API `substitute_pattern`](https://github.com/webmin/webmin/commit/1579671702bd31af70365f9c652dfbebbc2473dd) to be able to make various strings generation based on the unsafe pattern received from a user.

I will create a PR tomorrow for adding this on Virtualmin side, as now it's pretty trivial.

In other words, it will be possible for a user to set a pattern like **`[a-z]{1}-[0-9]{4}`** and get a random string like **`u-5302`**.

The full API description is also added on the commit. For the convenience I will post API description with all features here:

```Perl

=head2 substitute_pattern(regex-pattern, [&params])

Given regular expression generates a string based on the pattern. Hash reference
with params can be used to control default pattern length, results filtering and
replacement, date/time substitution and manipulate resulted string with callback

This function must be save to be used with patterns defined by a user to generate
strings with desired pattern, like usernames

Examples:

    Generate random MAC address
      - call   : substitute_pattern('[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}');
      - result : d3:18:2d:24:97:a7

    Generate random HEX string with 40 characters
      - call   : substitute_pattern('[a-f0-9]{40}');
      - result : b020475196675a88810321341f2578d32c634049

    Generate a username based on the pattern set by a user
      - call   : substitute_pattern('u-"[\d]{4}"-g[\d]', {'length' => 2, filter => '[^A-Za-z0-9\\-_]'})
      - result : u-6451-g98
      - desc   : even though a user sets a pattern for a username as 'u-"[\d]{4}"-g[\d]', the filter will
                 make sure that double quotes will be removed and a second matching group for a numerical
                 string will be set to length of two digits (default is one)

    Generate a username based on the pattern set by a user, checking if it exists using callback
      - call   : my $callback = sub {
                   my $user = shift;
                   if (user_exists($user)) {
                      return error("Error: User $user already exists!");
                   }
                   return $user;
                 };
                 my $pattern = 'user-[\d]{4}';
                 my $params = {'filter' => '[^A-Za-z0-9\\-_]', 'callback' => $callback};
                 substitute_pattern($pattern, $params);
      - result : user-4263 or error if user exists

    Generate filename substituting datetime template strings
      - call   : my $params = {'filter' => '[^A-Za-z0-9\\-_:]', 'substitute' => 'datetime'};
                 my $pattern = 'file-[\d]{4}--${year}-${month}-${day}_${hours}:${minute}:${seconds}';
                 substitute_pattern($pattern, $params); 
      - result : file-7385--2021-12-25_14:00:00
      - desc   : a `filter` param will make sure that in case the pattern is comming from the user all
                 disallowed characters will be discarded, and `substitute` datetime param will make sure
                 that the pattern variables such as `${year}` or `${days}` will be replaced accordingly

=cut

```

**Comment by tpnsolutions** [comment]
Sweet @iliarostovtsev that's awesome! Happy Holidays!

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, check [this PR](https://github.com/virtualmin/virtualmin-gpl/pull/345), all works for me after various of tests.

Description is on the PR.

**Comment by iliarostovtsev** [comment]
> I will create a PR tomorrow for adding this on Virtualmin side, as now it's pretty trivial.

I forgot to mention that I was wrong as adding [that PR](https://github.com/virtualmin/virtualmin-gpl/pull/345) wasn't trivial at all!
