### ISSUE TITLE
Scheduled Cron Jobs - show when cron.service is running

### ISSUE THREAD

**Issue by Sopor** [virtualmin/authentic-theme#1573]
Is it possible to show on the page `Scheduled Cron Jobs` if the cron.service is running or not?

It seems that mine wasn't running and i thought it was running when i could see my active cron jobs, but obvious i was wrong.

**Comment by iliarostovtsev** [comment]
Hi,

Yes, have a look at **System ⇾ Scheduled Cron Jobs ⇾ Configuration: Configurable options** and its **Display running status of jobs?** option, which can be set to **○ Yes, and allow starting and stopping ○ Yes ◉ No**.

**Comment by Sopor** [comment]
I think you misunderstood me. I don't want to see if the actual cron job is running. I want to see if the cron.service is running.

**Comment by jcameron** [comment]
Good suggestion - you should be able to see this at System -> Bootup and Shutdown, but we could also show it in the cron module.

**Comment by jcameron** [comment]
I have implemented this for inclusion in the next release of Webmin
