### ISSUE TITLE
The closing button missing when using desktop internet browser

### ISSUE THREAD

**Issue by TongTC** [virtualmin/authentic-theme#1575]
Dear  @iliarostovtsev  

Happy New year.

Please refer the picture below:

I would like to request suggestion to you about **File Transfer Status.**

The **closing button missing**(refer I point) when I use desktop internet browser .

How to config for  closing button come back ?

Best Regard.

![Untitled](https://user-images.githubusercontent.com/56378146/148902265-0a151125-7ae1-454f-bf40-3557bdb66f10.png)

**Comment by iliarostovtsev** [comment]
Hi,

Happy New Year.

The closing button must be there. I see it:

![image](https://user-images.githubusercontent.com/4426533/148921402-710d07b8-edbc-4e98-a8c0-91e096c7326b.png)

Try force reloading the page.

**Comment by TongTC** [comment]
OK , @iliarostovtsev  Thank you for your reply.

I will checked again.

Best Regard
