### ISSUE TITLE
Dashboard does not fully load if not active tab

### ISSUE THREAD

**Issue by My-Random-Thoughts** [virtualmin/authentic-theme#1579]
When opening lots of webmin tabs only the currently active tab will fully load the dashboard.  This can be seen by looking at the tab titles.  If you quickly cycle all the tabs the page will load fully.

Tab titles can be seen to change from `Webmin`  to  `Webmin 1.984`  and finally to  `Dashboard -- Webmin 1.984`.  The final dashboard change does not happen.

This may be a difficult one to diagnose! 

Webmin v1.984
Theme v19.84.7
Across different Linux and hardware types (Debian/Ubuntu, VM/Raspberry Pi)
Using Firefox 96 on Ubuntu 21.10

Thanks

**Comment by iliarostovtsev** [comment]
Hi,

This is not a bug but really a feature. 🙂

What is the problem of the page being loaded at a time of it being focused. We intentionally block any activity in background unless tab is focused/visible to prevent unnecessary calls to the server and possible server overload.

Although, some things are intelligently done by the browser, which I'm also happy about.

**Comment by My-Random-Thoughts** [comment]
Not a problem per-se, but I have 9 (so far) installations that I open occasionally to check for updates, etc.  I like to have them loading in the background while I finish something else.

If you know about it and it's intentional, fair enough.  :)

Thank you

**Comment by iliarostovtsev** [comment]
> If you know about it and it's intentional, fair enough.

The initial page load is what Chrome does.

> Not a problem per-se, but I have 9 (so far) installations that I open occasionally to check for updates

However, if you load the page fully first but still want it to be updated in the background, you can do this by going to **Theme Configuration: Dashboard and real-time monitoring** page and set **Enable real-time monitoring** to ** Yes, forced**.
